dataset_id: cmrp30fdp0120o007a69s3nfc
task: TTS
format: tsv
index_file: Burmese_41Hours_TTS_Dataset/metadata.tsv
base_audio_path: Burmese_41Hours_TTS_Dataset/audio/
columns:
  audio_path:
    source_column: file_name
    dtype: file_path
    file_extension: .wav
  transcription:
    source_column: sentence
  speaker_name:
    source_column: speaker_name
    dtype: category
  language:
    source_column: language
    dtype: category
  age:
    source_column: age
    dtype: int
  gender:
    source_column: gender
    dtype: category
  theme:
    source_column: theme
    dtype: category
  domain:
    source_column: domain
    dtype: category
  sentence_ID:
    source_column: sentence_ID
    dtype: category
root_strategy: index
