dataset_id: "cmihqro9h0238o207fgg5cmf6"
task: "TTS"
format: "csv"
encoding: "utf-8-sig"
checksum: "c29134fe715a9a794f44c94c36022f548e97d6551658bc02f9540e05c1f5f203"

index_file: "metadata.csv"
base_audio_path: "audios/"

columns:
  audio_path:
    source_column: "Audio File Name (.wav)"
    dtype: "string"
  transcription:
    source_column: "Transcript"
    dtype: "string"
  book:
    source_column: "Book (audio folder)"
    dtype: "category"
  speaker_id:
    source_column: "Pseudo ID"
    dtype: "category"
  gender:
    source_column: "Gender"
    dtype: "category"
    optional: true
  duration:
    source_column: "Duration"
    dtype: "float"
    optional: true

