dataset_id: cmrtehynr008qmm07wfw4q0ec
task: ASR
root_strategy: "index"
format: tsv
index_file: haz_asr_dataset/data.tsv
base_audio_path: haz_asr_dataset/
columns:
  audio_path:
    source_column: path
    dtype: file_path
  transcription:
    source_column: sentence
  video_id:
    source_column: video_id
    dtype: category
root_strategy: index
