dataset_id: "cmj2rze7r00j5ny07uhs85go2"
task: "TTS"
format: "tsv"
checksum: "4e48fe61ca87cfde0575f989ea81783701c32ddee126dc386b8736f40a643036"

index_file: "text.tsv"
base_audio_path: "clips/"

columns:
  audio_path:
    source_column: "clip_filename"
    dtype: "string"
  transcription:
    source_column: "text"
    dtype: "string"

