dataset_id: "cmiuimd7e01fimf072njn3mbb"
task: "TTS"
root_strategy: "paired_glob"
checksum: "87b46aec3d801d9981df9f92810e3a0ab8fff770f46686d6af13de76eb45f723"

file_pattern: "**/*.txt"
audio_extension: ".webm"