dataset_id: cmid4jner00hnnv072tkwlbps
task: TTS
root_strategy: paired_glob
checksum: "6612a021d2bb2320ebdf9ab1324dc35ce78b41baf30fb5bbea31c0f2784f93dd"

file_pattern: '**/*.txt'
audio_extension: .webm
