dataset_id: cmid4ekjn00b8nu07xonhj0x8
task: TTS
root_strategy: paired_glob
checksum: "bcc08f5db50149c4733df04c58cb3c4258bb2cb0f7e3e5b3a7fe557cf9526dda"

file_pattern: '**/*.txt'
audio_extension: .flac
