dataset_id: "cmmys9qyv00f4mf0794yqc63c"
task: "ASR"
format: "tsv"

index_file: "ss-corpus-fy-NL.tsv"
base_audio_path: "audios/"

columns:
  audio_path:
    source_column: "audio_file"
    dtype: "file_path"
  transcription:
    source_column: "transcription"
    dtype: "string"
  speaker_id:
    source_column: "client_id"
    dtype: "category"
    optional: true
  audio_id:
    source_column: "audio_id"
    dtype: "string"
    optional: true
  duration_ms:
    source_column: "duration_ms"
    dtype: "int"
    optional: true
  prompt_id:
    source_column: "prompt_id"
    dtype: "string"
    optional: true
  prompt:
    source_column: "prompt"
    dtype: "string"
    optional: true
  votes:
    source_column: "votes"
    dtype: "int"
    optional: true
  age:
    source_column: "age"
    dtype: "category"
    optional: true
  gender:
    source_column: "gender"
    dtype: "category"
    optional: true
  accents:
    source_column: "accents"
    dtype: "string"
    optional: true
  variant:
    source_column: "variant"
    dtype: "string"
    optional: true
  language:
    source_column: "language"
    dtype: "category"
    optional: true
  prompt_upvotes:
    source_column: "prompt_upvotes"
    dtype: "int"
    optional: true
  prompt_reports:
    source_column: "prompt_reports"
    dtype: "int"
    optional: true
  is_edited:
    source_column: "is_edited"
    dtype: "int"
    optional: true
  split:
    source_column: "split"
    dtype: "category"
    optional: true
  char_per_sec:
    source_column: "char_per_sec"
    dtype: "float"
    optional: true
  quality_tags:
    source_column: "quality_tags"
    dtype: "string"
    optional: true
